### ISSUE TITLE
cleancss value.split is not a function breaks

### ISSUE THREAD

**Issue by negherbon** [jakubpawlowicz/clean-css#887]
Last time i run the build in my company project was 8 days ago and after this are occurring this error bellow:

<img width="897" alt="captura de tela 2017-02-07 as 15 45 28" src="https://cloud.githubusercontent.com/assets/5859119/22703838/b9454bd4-ed4c-11e6-9fa8-f0f9725005bc.png">

It's happening this error with someone?

**Comment by negherbon** [comment]
My mistake :)

**Comment by jakubpawlowicz** [comment]
No worries!

**Comment by ernestoalejo** [comment]
What was the mistake here? I have this error too with this input:

```css
@import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Rasa');
```

**Comment by Manu1400** [comment]
Please, reopen this issue.

**Comment by jakubpawlowicz** [comment]
@ernestoalejo @Manu1400 @negherbon any further details here?

**Comment by ernestoalejo** [comment]
Sorry, I don't remember the details of this error. I have checked the commits of that day and there's one updating from `gulp-clean-css` `^2.0.12` to `^3.0.2`; but I can't reproduce the issue even when forcing the version 3.4.12 of this package.

**Comment by jakubpawlowicz** [comment]
Thanks @ernestoalejo for giving it a try - @Manu1400?

**Comment by jakubpawlowicz** [comment]
Ping!

**Comment by ivanreese** [comment]
I'm getting this error too, using the latest [gulp-clean-css](http://npmjs.com/package/gulp-clean-css), which is currently using clean-css 4.1.5.

Here's how I'm invoking clean-css — I hope you can read coffeescript!

```coffee
.pipe gulp_clean_css
  level:
    1:
      removeEmpty: false
```

If I set `removeEmpty: true`, that fixes the error. I can mix in all other sorts of other optimization configurations (eg: O2 on and off, various other O1 options on or off), and that doesn't seem to affect the issue.

Here's my stack trace.

<img width="1018" src="https://user-images.githubusercontent.com/2061924/27978877-60a16414-632f-11e7-9b23-26324f5f8658.png">

The input CSS file doesn't seem to matter. I've tested it with a bunch of different kinds of input, including a completely empty file. All of them break in the same way, as best as I can tell.

Let me know if there's anything else I can do to help repro.

**Comment by jakubpawlowicz** [comment]
I've found an edge case in serializing code and will push it with 4.1.6. Hopefully it solves the problem.

**Comment by jakubpawlowicz** [comment]
Fixed in 4.1.6.

**Comment by michaeldemille** [comment]
Hi, I'm getting a similar issue when I try to build my angular project.  It's a fairly large project, and I'm not sure what exactly I'm looking for that could be breaking the build.  If you could give me any direction as to what could possibly cause this issue in my .scss code, that would be greatly appreciated.

Thanks,

<img width="1093" alt="Screen Shot 2019-09-26 at 7 05 06 AM" src="https://user-images.githubusercontent.com/15610805/65690354-15c62200-e02c-11e9-80f8-43ef2074f1bb.png">

**Comment by michaeldemille** [comment]
A little bit more information about the above project.  It is an ionic 4 angular 8 project.  The above error occurs when I run the ng build --prod script.  I thought it might be something syntax related from recent code commits to the .scss files, so I ran js-beautify on the .scss files to clean them up, and it's still having the same error.

**Comment by michaeldemille** [comment]
Here are the default settings that the cleancss-webpack-plugin.js file is using from the angular setup.

`const cleancss = new CleanCSS({
                compatibility: 'ie9',
                level: {
                    2: {
                        skipProperties: [
                            'transition',
                            'font',
                        ]
                    }
                },
                inline: false,
                returnPromise: true,
                sourceMap: this._options.sourceMap,
            });`

**Comment by michaeldemille** [comment]
if I change the removeEmpty option to false, then the error turns into this: 

![image](https://user-images.githubusercontent.com/15610805/65713598-bf220d80-e056-11e9-9450-24d28e711d28.png)

**Comment by michaeldemille** [comment]
I found the problem.  It ended up being caused by a missing semi-colon in my scss: 

![image](https://user-images.githubusercontent.com/15610805/65718524-eed61300-e060-11e9-8b91-b8a4332fd2da.png)

which caused value to be an array instead of a string.

![image](https://user-images.githubusercontent.com/15610805/65719306-c9e29f80-e062-11e9-83db-ba0f8c3ff822.png)
